name: MCPACK

on:  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag'
        required: true
        default: 'v'
        
env:
  REPO: '${{ github.event.repository.name }}'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set variables
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        NAME="$REPO_$VERSION"
        echo "NAME=$NAME" >> $GITHUB_ENV

    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: '${{ env.NAME }}'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '${{ env.NAME }}'
        name: '${{ env.REPO }}'
        tag: '${{ env.VERSION }}'
        token: ${{ secrets.GITHUB_TOKEN }}
