name: MCPACK

on:  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'vX.X.X.X-X-X.X.X'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'BlockSplit.mcpack'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "BlockSplit.mcpack"
        tag: '${{ github.event.inputs.version }}'
        token: ${{ secrets.GITHUB_TOKEN }}
